const healthCareConfig = [{ label: "HealthCare Staffing", imageSrc: "https://www.bistatechnologies.com/static/Temporary-Staffing.jpg", description: "Opusing is a pioneering and market-leading provider of workforce solutions and healthcare staffing services. Our strategies leverage our more than 15 years of experience, knowledge, and insight to help customers overcome complex labor-related problems while retaining high-quality results. We are committed to finding and hiring highly skilled healthcare workers in every specialty and field of study. Whatever the need, we have established the most extensive and qualified network of healthcare experts in the country. We provide various specialty recruiting options and assignment lengths, including permanent placements, for nurses and related professions, as well as doctors and advanced practice providers. In a way, we are streamlining the way healthcare organizations procure supplemental staff.", css: "lg:flex bg-sky-50 " },
{ label: "Permanent Placement", imageSrc: "https://www.bistatechnologies.com/static/permanent.webp", description: "Opusing is a pioneering and market-leading provider of workforce solutions and healthcare staffing services. Our strategies leverage our more than 15 years of experience, knowledge, and insight to help customers overcome complex labor-related problems while retaining high-quality results. We are committed to finding and hiring highly skilled healthcare workers in every specialty and field of study. Whatever the need, we have established the most extensive and qualified network of healthcare experts in the country. We provide various specialty recruiting options and assignment lengths, including permanent placements, for nurses and related professions, as well as doctors and advanced practice providers. In a way, we are streamlining the way healthcare organizations procure supplemental staff.", css: "lg:flex flex-row-reverse bg-pink-50" },
{ label: "Travel Nursing", imageSrc: "https://www.bistatechnologies.com/static/travel.webp", description: "Opusing is a pioneering and market-leading provider of workforce solutions and healthcare staffing services. Our strategies leverage our more than 15 years of experience, knowledge, and insight to help customers overcome complex labor-related problems while retaining high-quality results. We are committed to finding and hiring highly skilled healthcare workers in every specialty and field of study. Whatever the need, we have established the most extensive and qualified network of healthcare experts in the country. We provide various specialty recruiting options and assignment lengths, including permanent placements, for nurses and related professions, as well as doctors and advanced practice providers. In a way, we are streamlining the way healthcare organizations procure supplemental staff.", css: "lg:flex bg-gray-50" },
{ label: "Locum Tenens", imageSrc: "https://www.bistatechnologies.com/static/locum.webp", description: "Opusing is a pioneering and market-leading provider of workforce solutions and healthcare staffing services. Our strategies leverage our more than 15 years of experience, knowledge, and insight to help customers overcome complex labor-related problems while retaining high-quality results. We are committed to finding and hiring highly skilled healthcare workers in every specialty and field of study. Whatever the need, we have established the most extensive and qualified network of healthcare experts in the country. We provide various specialty recruiting options and assignment lengths, including permanent placements, for nurses and related professions, as well as doctors and advanced practice providers. In a way, we are streamlining the way healthcare organizations procure supplemental staff.", css: "lg:flex flex-row-reverse  bg-green-50" }
]

const healthcareCardsConfig = [{ heading: "Expertise", description: "Years of experience in the healthcare staffing industry.", imageSrc: "https://www.bistatechnologies.com/static/ex.webp", css: "border-2 hover:border-gray-400", animationTime: 0 },
{ heading: "Quality Assurance", description: "Rigorous screening process for the best candidates.", imageSrc: "https://www.bistatechnologies.com/static/qa.png", css: "border-2 hover:border-green-700", animationTime: 200 },
{ heading: "Personalized Service", description: "Understanding your specific needs to find the right match.", imageSrc: "https://www.bistatechnologies.com/static/ps.png.crdownload", css: "border-2 hover:border-sky-700", animationTime: 300 },
{ heading: "24/7 Support", description: "Available around the clock for any staffing emergencies.", imageSrc: "https://www.bistatechnologies.com/static/ser.png", css: `border-2 hover:border-orange-600`, animationTime: 400 }
]
export { healthCareConfig, healthcareCardsConfig }