const nonItStaffingConfig = [
    { heading1: "Elevate Your Business with Expert Finance Staffing", heading2: "Finance", imageSrc: "https://www.bistatechnologies.com/static/Frugal%20Tip%20of%20the%20Day!.jpeg", description: "At Bista Technologies, we specialize in top-tier non-IT staffing, with a strong focus on finance resource hiring. We understand that finance professionals are critical to your business's success, and our rigorous selection process ensures you get the best talent tailored to your needs.Our expertise in the finance sector allows us to provide staffing solutions that align with your goals, connecting you with skilled professionals, from analysts to CFOs, who seamlessly fit into your team.Partnering with Bista Technologies means more than just filling roles; it's about elevating your business with exceptional financial talent. Trust us to deliver reliable, efficient, and high-quality staffing solutions that help you achieve your business objectives.", cardCss: "lg:flex bg-slate-50", headingCss: "text-sky-600 bg-sky-100" },
    { heading1: "HR Excellence", heading2: "Human Resource", imageSrc: "https://www.bistatechnologies.com/static/CIO%20Review_%2020%20Most%20Promising%20HR%20Technology%20Solution%20Providers%20in%202017.jpeg", description: "Bista Technologies specializes in non-IT staffing solutions, with a strong emphasis on human resource hiring. Our dedicated team understands the unique needs of HR roles, ensuring we match you with candidates who excel in recruitment, employee relations, and organizational development. We provide comprehensive support to find professionals who align with your company culture and contribute to your strategic goals. With our extensive network and rigorous selection process, we guarantee top-tier HR talent. Trust Bista Technologies to enhance your HR capabilities and drive your business success.", cardCss: "lg:flex flex-row-reverse bg-purple-50", headingCss: "text-orange-500 bg-orange-200" },
    { heading1: "Industrial Support", heading2: "Light Industry", imageSrc: "https://www.bistatechnologies.com/static/Who%20Is%20The%20Best%20Electrician%20on%20Long%20Island_.jpeg", description: "Light industrial work supports many industries in the world’s distribution system. These positions typically involve tasks from areas of manufacturing, assembly, and other types of manual labor. Nearly every product we use in our day-to-day lives has come from some sort of large or small-scale industrial work. Light industrial workers may be responsible for tasks such as assembling products, packaging goods, operating machinery, and loading/unloading materials. They may also be involved in quality control and inspecting products. These essential positions often involve substantial physical labor and workers may be required to lift heavy objects. As the goal of light industrial work is to help with the production and distribution of goods, many skilled professionals can experience growth from the production floor to quality assurance and even managerial positions.", cardCss: "lg:flex bg-slate-50", headingCss: "text-green-600 bg-green-100" },
]

const nonItCardsConfig = [
    { heading: "Compliance and regulatory support", description: "Stay ahead of regulatory changes with our expert compliance and regulatory support. Our team provides guidance on industry-specific regulations, ensuring your business is compliant and secure. With our support, you can focus on growth while we handle the complex compliance requirements", imageSrc: "https://www.bistatechnologies.com/static/Streamlining%20Operations_%20The%20Power%20of%20Business%20Process%20Outsourcing.jpeg", css: "border-2 hover:border-gray-400", animationTime: 0 },
    { heading: "Fill critical skill gaps", description: "Stay ahead of regulatory changes with our expert compliance and regulatory support. Our team provides guidance on industry-specific regulations, ensuring your business is compliant and secure. With our support, you can focus on growth while we handle the complex compliance requirements.", imageSrc: "https://www.bistatechnologies.com/static/How%20Busy%20Marketers%20Can%20Make%20Money%20on%20the%20Side%20_%20Entrepreneur.jpeg", css: "border-2 hover:border-green-700", animationTime: 200 },
    { heading: "Reduce recruitment costs", description: "Reduce recruitment costs and boost your bottom line with our expert solutions. Our team streamlines your hiring process, eliminating unnecessary agency fees and saving you time and resources. By leveraging our expertise, you can achieve significant cost savings and make more informed hiring decisions.", imageSrc: "https://www.bistatechnologies.com/static/5%20Cost-cutting%20Strategies%20To%20Save%20Money%20On%20Business%20Expenses.jpeg", css: "border-2 hover:border-sky-700", animationTime: 300 },
    { heading: "Improve productivity and efficiency", description: "Maximize your team's potential with our expert solutions to improve productivity and efficiency. Our cutting-edge tools and strategies help you streamline processes, reduce waste, and boost employee morale. By leveraging our expertise, you can achieve significant gains in productivity and efficiency.", imageSrc: "https://www.bistatechnologies.com/static/How%20to%20Take%20Breaks%20That%20Help%20You%20Have%20the%20Most%20Productive%20Workday%20-%20Thrive%20Global.jpg", css: "border-2 hover:border-sky-700", animationTime: 300 },
]
export { nonItStaffingConfig, nonItCardsConfig }